### ISSUE TITLE
Recent IdeaVim plugin update breaks intellimacs leader key

### ISSUE THREAD

**Issue by ivanbokii** [MarcoIeni/intelli-space#57] opened 2024-01-30 21:10 UTC
IdeaVim update v2.8.0, after installation, SPC stops working as a leader key and behaves just as a regular space button. Reverting plugin to 2.7.5 fixes the problem

**Comment by marcoieni** [comment] 2024-01-30 21:12
I don't have time to look into this. But if somebody figures it out, I'll review and test the PR 👍

**Comment by klochowicz** [comment] 2024-01-30 21:14
Same here.

 I believe it's related to broken sourcing of external files in the `.ideavimrc`: 

https://youtrack.jetbrains.com/issue/VIM-3273/Config-file-stoped-working

**Comment by marcoieni** [comment] 2024-01-30 21:19
ok, so it seems the issue is not in intellimacs.

The workaround is to downgrade to IdeaVim 2.7.5 while we wait for a fix on their side.

**Comment by gquittet** [comment] 2024-02-01 15:42
We can close the issue, the version 2.8.2 released today of IdeaVim is fixing this issue 🎉

**Closed as completed** 2024-02-01 17:40 UTC
